id: A80FDF787
title: CI_ยง69
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:03:38.841557
  last_modified_at: 2022-03-01 23:03:38.841564
